backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Description,
                    name: description,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
          - {
              label: Philosophy,
              name: philosophy,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Description,
                    name: description,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                ],
            }
          - {
              label: Services,
              name: services,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Description,
                    name: description,
                    widget: list,
                    fields:
                      [{ label: Paragraph, name: paragraph, widget: text }],
                  },
                  {
                    label: Packages,
                    name: packages,
                    widget: list,
                    fields:
                      [
                        { label: Title, name: title, widget: text },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  {
                    label: Testimonials,
                    name: testimonials,
                    widget: list,
                    fields:
                      [
                        { label: Author, name: author, widget: text },
                        { label: Quote, name: quote, widget: text },
                      ],
                  },
                ],
            }
      - file: "content/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "content/pages/services.md"
        label: "Services"
        name: "services"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "services-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
